[package]
name = "dotcom"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.4.10"
rocket_contrib = { version="0.4.10", default-features=false, features=["tera_templates"] }
tera = "1.12.0"
pulldown-cmark = "0.8.0"
serde = "1.0.126"
serde_json = "1.0.59"
lazy_static = "1.4.0"
