[package]
name = "dotcom"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
tera = "1.12.0"
handlebars = "4.1.3"
pulldown-cmark = "0.8.0"
glob = "0.3.0"
serde_json = "1.0.64"
lazy_static = "1.4.0"
notify = "4"
tokio = "1.12"
